// Generated by Wrangler on Fri May 10 2024 15:18:57 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

type ImportMessage = {
	url: string
	ws_id?: string
	content?: string
  };

interface Env {
	test_queue_binding: Queue<ImportMessage>
	websocket_server: DurableObjectNamespace;
}
