name = "cf-limit-repro"
main = "src/index.ts"
compatibility_date = "2024-05-02"

[[durable_objects.bindings]]
  name = "link_limit"
  class_name = "LinkManager"

[[migrations]]
  tag = "v1"
  new_classes = ["LinkManager"]

